[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "Davide De Marchi", email = "davide.de-marchi@ec.europa.eu"}]
dynamic = ["version", "description"]
