BASE_URL = 'http://141.227.140.197/'

PREFIX = 'dts/'

GENERAL_ENDPOINT = BASE_URL + PREFIX

VECTOR_ENDPOINT = GENERAL_ENDPOINT + 'vector/'
RASTER_ENDPOINT = GENERAL_ENDPOINT + 'raster/'
REDIS_ENDPOINT = GENERAL_ENDPOINT + 'redis/'
